version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb_local
    restart: unless-stopped
    ports:
      - "27017:27017"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongodb
