# because it structured config, make item clear and modern works well with pydantic v2


[jwt_config]
SECRET_KEY = "xxxxxxxxxxxx"
ALGORITHM = "HS256"
EXPIRE_MINUTES = 30

[mongodb_config]
MONGODB_URL = "mongodb://localhost:27017"
MONGODB_DATABASE = "test"

[cors_config]
ORIGINS = ["*"]

[rate_limit_config]
MAX_REQUESTS = 10
WINDOW_SEC = 60


